### ISSUE TITLE
Installation guide and ressources

### ISSUE THREAD

**Issue by Jejebond** [beecho01/material-symbols#6]
**Describe the bug**
Adding this code in configuration.yaml result in a **board reset**:

```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/material-symbols/material-symbols.js
      type: module
```

**Expected behavior**
The installation guide should explain or send back to an official guide on how to add a ressource to UI controlled boards.
Not sure if my interpretation is right though.

(PS: I had a backup 😊)
